export const VERSION_HISTORY = [
  {
    version: '1.14.1',
    fecha: '2026-09-22',
    titulo: 'Fix: reconfiguración de puertos y patrón de URL mobile',
    cambios: [
      'Puertos Docker: PostgreSQL 6112, Backend 6111, Nginx 6110, Metro 6109, Vite 6108',
      'Mobile: una sola URL hardcoded (sin debug/release), patrón adoptado de insectos beneficos',
      'normalizeApiUrl: acepta solo IP y auto-completa http://IP:6111/api/v1',
      'network_security_config: cleartext HTTP permitido para cualquier IP',
      'ServerCheckScreen: gateway obligatorio antes del login',
      'Documentación: AGENTS.md, README.md y SDD actualizados con nuevos puertos',
    ],
  },
  {
    version: '1.14.0',
    fecha: '2026-09-08',
    titulo: 'Reporte PDF: mejora de UX/UI y fix de descarga en mobile',
    cambios: [
      'Fix descarga de PDF en mobile: ReactNativeBlobUtil.statusCode undefined → verificación por magic bytes PDF',
      'PDF: tablas de Información General y Servicio reorganizadas en 2 columnas compactas (4 col: label1|val1|label2|val2)',
      'PDF: sección de accesorios reorganizada en grid 2 columnas',
      'PDF: color de celdas label con fondo azul claro (LABEL_BG) para mejor legibilidad',
      'PDF: alineación de títulos de sección a la izquierda',
      'PDF: fotos reducidas 25% (128×98 px) para mayor densidad por hoja',
      'PDF: hoja 2 = recepción equipo + recepción accesorios (por separado, sin duplicados)',
      'PDF: hoja 3 = devolución equipo + devolución accesorios (nueva)',
      'PDF: extracción de addPageHeader() para reutilizar en las 3 hojas',
    ],
  },
  {
    version: '1.13.1',
    fecha: '2026-09-07',
    titulo: 'Fix: bugs en Crear PSR (sedes, DatePicker, error 500)',
    cambios: [
      'Selector de sede ahora muestra solo sedes activas',
      'DatePicker: corrección de crash "cannot read property dismiss of undefined"',
      'Fix error 500 al crear PSR (setters LocalDate duplicados eliminados)',
    ],
  },
  {
    version: '1.13.0',
    fecha: '2026-09-06',
    titulo: 'HDT-016 — Corrección PSR/OSR y catálogo de áreas',
    cambios: [
      'El formulario Agregar OSR muestra fecha PSR, fechas de uso y meses calculados',
      'Nueva OSR inicia con número y costo vacíos; editar OSR conserva sus datos',
      'Nuevo catálogo Áreas con Recepción Packing, Almacén de Materiales, Frío y Cámara de Producto Terminado',
      'Selector de área al crear y editar usuarios en web y mobile',
      'Tarjetas de usuarios mobile muestran el nombre y el área debajo',
      'CRUD de áreas en web y mobile con activación, desactivación y eliminación',
      'Reporte PDF corporativo de dos páginas disponible para equipos DEVUELTO desde Detalles de equipo',
    ],
  },
  {
    version: '1.12.0',
    fecha: '2026-08-26',
    titulo: 'HDT-015 — PSR 1:N OSR (múltiples OSR por PSR)',
    cambios: [
      'Una PSR puede contener múltiples OSR (ilimitado), antes era 1:1',
      'PSR con estados ACTIVO / PARCIAL (x/N finalizadas) / FINALIZADO (todas devueltas)',
      'Card PSR muestra lista de OSRs con costo, equipo, estado y acciones por OSR',
      'Agregar OSR ilimitado y eliminar OSR individual (solo si no tiene equipo)',
      'Editar OSR (costo/moneda) vía PUT /osr/{id}',
      'Ingreso de equipo por OSR específica (SelectPsrEquipment lista OSRs pendientes)',
      'Datos históricos compatibles: PSRs existentes pueden agregar más OSRs',
    ],
  },
  {
    version: '1.11.1',
    fecha: '2026-08-18',
    titulo: 'Desactivar/Activar catálogos desde web y mobile (soft delete)',
    cambios: [
      'Botón desactivar/activar en catálogos (marcas, proveedores, tipos de equipo, sedes, motivos PSR) en web y mobile',
      'Los registros referenciados se desactivan en lugar de eliminarse (soft delete)',
      'Indicador "Inactivo" en la app para registros desactivados',
    ],
  },
  {
    version: '1.11.0',
    fecha: '2026-08-17',
    titulo: 'HDT-014 — Timeline dinámico de detalle de equipo',
    cambios: [
      'Nueva pantalla "Historial del Equipo" accesible desde el botón "Ver Historial" en el listado',
      'Endpoint backend GET /api/v1/equipos/{id}/timeline (consolidación de eventos PSR/OSR/ingreso/averías/reparaciones/finalización)',
      'Resumen operativo: fecha de ingreso, horómetro inicial/final, cantidad de averías, tiempo de inactividad y fecha de finalización',
      'Timeline expandible por evento con detalle, estado y evidencias (fotos ampliables)',
    ],
  },
  {
    version: '1.10.1',
    fecha: '2026-08-13',
    titulo: 'HDT-013 — Fix registro de token FCM al abrir la app',
    cambios: [
      'Registro del token FCM al iniciar la app con sesión persistente',
      'Re-registro automático del token cuando FCM lo rota (onTokenRefresh)',
    ],
  },
  {
    version: '1.10.0',
    fecha: '2026-08-13',
    titulo: 'HDT-013 — Notificaciones push ampliadas',
    cambios: [
      'Plantilla de notificación nueva: Evento / Proveedor - Codigo / Registrado por',
      'Notificación al registrar una avería',
      'Notificación al atender una avería',
      'Notificación al finalizar el servicio (devolución)',
      'Corrección de warnings FCM deprecados (API v22)',
      'Navegación al detalle del equipo al tocar la notificación',
    ],
  },
  {
    version: '1.9.0',
    fecha: '2026-08-11',
    titulo: 'HDT-012 — UX operativo, evidencias, contraseña y sync de catálogos',
    cambios: [
      'Identificadores operativos en mayúsculas (número PSR, código, modelo, serie, guía de remisión)',
      'Layout de averías en detalle: fecha reporte → atención y horómetros',
      'Fecha y hora de atención editable y validada',
      'Sync de motivos PSR → tipos de equipo (find-or-create al crear)',
      'Evidencias de ingreso ampliadas (4 vistas + extintor) y de devolución por accesorios',
      'Máximo 5 fotos por avería y 2 evidencias obligatorias al atender',
      'Contraseña de exactamente 8 dígitos (DNI)',
      'PSR/OSR finalizado read-only',
      'Fix de eliminación de usuarios (trigger Super Admin V29)',
    ],
  },
  {
    version: '1.8.0',
    fecha: '2026-08-10',
    titulo: 'HDT-011 — Horómetro en averías y trazabilidad de usuario',
    cambios: [
      'Horómetro en registro y atención de averías con días de inactividad',
      'Trazabilidad de usuario_creacion/usuario_actualizacion desde el JWT',
      'Fix 409 al devolver equipos',
      'Super Admin protegido por trigger de base de datos',
    ],
  },
  {
    version: '1.7.0',
    fecha: '2026-08-10',
    titulo: 'HDT-010 — Usuarios mobile simplificado',
    cambios: [
      'Creación de usuarios con solo Nombre obligatorio y Ubicación desde Sedes',
      'Rol "Usuario" por defecto al crear sin rol',
    ],
  },
  {
    version: '1.6.0',
    fecha: '2026-08-10',
    titulo: 'HDT-009 — Teclado móvil no cubre los inputs',
    cambios: [
      'KeyboardAwareScrollView en pantallas con formularios y diálogos',
      'Footer fijo en formulario de equipos',
    ],
  },
  {
    version: '1.5.0',
    fecha: '2026-08-06',
    titulo: 'HDT-008 — Desplegables, catálogos en tiempo real y referencias PSR/OSR',
    cambios: [
      'AppSelect con Portal y ScrollView completo',
      'Catálogos sincronizados en tiempo real entre dispositivos',
      'Card PSR/OSR en detalle de equipo y Marca/Modelo/GRR',
      'CRUD completo de campañas mobile y tab Catálogos por permisos',
    ],
  },
  {
    version: '1.4.0',
    fecha: '2026-07-24',
    titulo: 'HDT-007 — CRUD de usuarios mobile',
    cambios: [
      'Crear y editar usuarios desde la app',
      'Permisos por rol (solo Super Admin edita Super Admin)',
      'Correcciones de autenticación (login y logout robustos)',
    ],
  },
  {
    version: '1.3.0',
    fecha: '2026-07-09',
    titulo: 'HDT-006 — Gestión móvil de PSR/OSR',
    cambios: [
      'Crear y editar PSR/OSR con date picker nativo',
      'Catálogos integrados (campañas, sedes, motivos)',
    ],
  },
  {
    version: '1.2.0',
    fecha: '2026-07-08',
    titulo: 'HDT-004 — Pantallas mobile faltantes',
    cambios: [
      'Catálogos (marcas, proveedores, tipos, sedes, motivos)',
      'Roles, usuarios, auditoría y configuración',
      'Tab Catálogos con menú de botones',
    ],
  },
  {
    version: '1.1.0',
    fecha: '2026-07-08',
    titulo: 'HDT-003 — Calidad, despliegue y auditoría',
    cambios: [
      'Tests backend, frontend y mobile',
      'Módulo de auditoría de eventos',
      'Configuración CORS/seguridad y CI/CD',
      'Modo claro/oscuro en el frontend web',
    ],
  },
  {
    version: '1.0.0',
    fecha: '2026-05-29',
    titulo: 'Base del sistema',
    cambios: [
      'Infraestructura Docker (PostgreSQL 18, Quarkus, Nginx)',
      'Autenticación local BCrypt + JWT',
      'Usuarios, roles, sedes y campañas',
      'Núcleo operativo: tipos de equipo, proveedores, marcas, equipos y averías',
      'Aplicación Android inicial',
    ],
  },
]
